# Generated by Django 2.0.2 on 2019-06-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='course_image',
        ),
    ]
