# Generated by Django 2.0.2 on 2019-06-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190607_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('associated_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='wd',
            field=models.ManyToManyField(blank=True, to='course.WikiData'),
        ),
    ]
