# Generated by Django 2.0.2 on 2019-06-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190608_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidata',
            name='associated_course',
        ),
    ]
