# Generated by Django 2.0.2 on 2019-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursepart_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidata',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='wikidata',
            name='url',
        ),
        migrations.AddField(
            model_name='wikidata',
            name='associated_course_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikidata',
            name='code',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
